---
- name: install and configure apache
  hosts: server2
  tasks:
    - name: collecting public ip of server
      command: curl http://169.254.169.254/latest/meta-data/public-ipv4
      register: myip
      
    - name: assigning publiic ip to a dynamic variable using set_fact
      set_fact: mypublicip="{{myip.stdout}}"

    - name: installing apache package
      yum:
        name: httpd
        state: present

    - name: enabling httpd service
      service:
        name: httpd
        enabled: yes

    - name: copying index.html
      template:
        src: index.html
        dest: /var/www/html
      notify: apache restart

    - name: modifying httpd.conf file
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#ServerName www.example.com'
        replace: 'ServerName {{mypublicip}}'
      notify: apache restart

  handlers:
    - name: apache restart
      systemd:
        name: httpd
        state: restarted
